### PR TITLE
feat: PR linting bot that provides user feedback as comments

### PR DESCRIPTION
**Pull request by Krande**
I also changed the figure paths in the template.md document to relative paths instead of hardcoded urls.

### CODE REVIEW

**Comment by Krande** [comment]
The bots that will be adding labels/comments won't work until we merge unfortunately :)

**Comment by VegarRingdalAibel** [comment]
Nice, will have a look tomorrow or monday 👍

**Comment by VegarRingdalAibel** [comment]
> The bots that will be adding labels/comments won't work until we merge unfortunately :)

Will it have more access after its merged?
Or does it not work since you do not have access to set labels to begin with?

image

**Comment by Krande** [comment]
> From what i can see we need to create github-app for actions to work with write access

This is solved by using `pull_request_target`

```
on:
  pull_request_target:
    types: [ opened, synchronize, edited, labeled ]
    branches:
      - main
```

Have tried and tested this on https://github.com/Krande/app-test

**Comment by VegarRingdalAibel** [comment]
@Krande 
Just tell me when you have updated to `pull_request_target` and added the other stuff you showed me yesterday 👍

**Comment by Krande** [comment]
Hey, as discussed we can further develop this in a separate org until it is more mature :)

**Pull request closed without merging**
